![alt text](https://github.com/callysto/callysto-sample-notebooks/blob/master/notebooks/images/Callysto_Notebook-Banner_Top_06.06.18.jpg?raw=true)

## Basic math operations

From the [International Math modelling challenge](https://immchallenge.org/Contests/index.html), looking at the [winning paper](https://immchallenge.org/Contests/2017/2017057.pdf) for 2017 [Jet lag problem](https://immchallenge.org/Contests/2017/Problem.html), this is productivity metric that was used:


![](images/question.png)

As part of this notebook we will demonstrate some basic  math calculations in Python, calculating the  first part of this metric - Jet lag Component:

$$ J  = \sqrt{\frac{1}{|M|}\sum_{m=1}^{M}P_{m}^2 }$$

$$ P_{m} = min\big\{ 10,\;10+6\; \cos \big( \frac{\pi\Delta J_{m}}{12}-\frac{\pi}{24}  \big) \big\} $$
We will  use random input data just for demonstration purposes.  

We will write formulas in Jupyter notebook markdown cells using LateX   
(Basic LateX tutorial is located  at **getting-started/tutorials/JupyterTestdrive-LateX.ipynb**,
 Latex cheat sheet is [here](http://tug.ctan.org/info/symbols/comprehensive/symbols-a4.pdf))

### Import the numpy library
[NumPy](http://www.numpy.org) is the fundamental package for scientific computing with Python.  
[quick-start tutorial](https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html)

In [1]:
import numpy as np

## Part 1
First we calculate $P_{m}$ from this formula:
$$ P_{m} = \min\left\{ 10,\;10+6\; \cos \left( \frac{\pi\Delta J_{m}}{12}-\frac{\pi}{24}  \right) \right\} $$

We need to define number of members M. Lets set it to 4.

In [2]:
M = 4

### Vectors and matricies
(Calculating  $\Delta J_{m}$)  
$\Delta J_{m}$ is shift in time zones for a given memeber m.   
To demonstrate how to work with vectors -  we will define origin time : **time1** and destination time: **time2** for every memeber, subract them and calculate the delta. 
 
To create vectors we will use [np.array()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)
It can be used to create 1- and multi-dimensional arrays.

In [3]:
#just randomly assigning times - vectors have size 4 - number of members M
time1 = np.array([1,2,3,4])
time2 = np.array([1,1,1,0])
print(type(time1), time1)
print(type(time2), time2)

<class 'numpy.ndarray'> [1 2 3 4]
<class 'numpy.ndarray'> [1 1 1 0]


To  subtract one vector from another we can just minus sign.  
[Other numerical operations on arrays](http://scipy-lectures.org/intro/numpy/operations.html)

In [4]:
delta = time1 - time2
print(delta)

[0 1 2 4]


Working with 2 dimentions,it's handy to use [np.matrix()](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matrix.html). More examples of ndarrays and matricies [here](https://www.python-course.eu/matrix_arithmetic.php)

### Pi and other constants
Going back to the formula: $$ P_{m} = \min\left\{ 10,\;10+6\; \cos \left( \frac{\pi\Delta J_{m}}{12}-\frac{\pi}{24}  \right) \right\}, $$  to calculate $P_{m}$ we need to $\pi$, cos  and min.

**$\pi$** is defined as constant **np.pi**   
[Full list of NumPy constants](https://docs.scipy.org/doc/numpy/reference/constants.html)

In [5]:
print(np.pi)

3.141592653589793


### Math functions
[Full list of NumPy math functions](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html)
#### Cosine
(Calculating $ 6\; \cos \left( \frac{\pi\Delta J_{m}}{12}-\frac{\pi}{24}  \right)  $ )

To calculate cosine we will use [np.cos()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cos.html) (as input it takes values in radians).  

In [18]:
first_part=6 * np.cos(np.pi * delta / 12 - np.pi / 24)
print(first_part)

[5.94866917 5.94866917 5.5432772  3.65256857]


#### Minimum.
(Calculating $\min\left\{ 10,\;10+6\; \cos \left( \frac{\pi\Delta J_{m}}{12}-\frac{\pi}{24}  \right) \right\}$)  
We will use [np.minimum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.minimum.html) to calcutae minimum.

In [19]:
p=np.minimum(10, 10 + first_part)
print(p)

[10. 10. 10. 10.]


## Recap
We have calculated the first part of the Jet Lag Component: $$ P_{m} = \min\left\{ 10,\;10+6 \; \cos \left( \frac{\pi\Delta J_{m}}{12}-\frac{\pi}{24}  \right) \right\} $$ using following code and assigning random initial values:

In [20]:
import numpy as np
M=4
time1 = np.array([1,2,3,4])
time2 = np.array([1,1,1,0])
delta=time1-time2
first_part=6*np.cos(np.pi*delta/12-np.pi/24)
p=np.minimum(10,10+first_part)
print(p)

[10. 10. 10. 10.]


## Part 2
Next we are going to calculate the second part of Jet Lag Component: $$ J  = \sqrt{\frac{1}{|M|}\sum_{m=1}^{M}P_{m}^2 }$$
To do it we need to find way how to calculate power, absolute value, summary and square root.

#### Power
(Calculating $P_{m}^2$)    
To calculate power of two for the vector - we can use [np.power()](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.power.html)

In [21]:
p_power2=np.power(p, 2)
print(p_power2)

[100. 100. 100. 100.]


Alternatively, we can use a common Python for powers denoted with two asterix like `**`. This is shown below

In [22]:
p_power2 = p**2
print(p_power2)

[100. 100. 100. 100.]


#### Summary
(Calculating $\sum_{m=1}^{M}P_{m}^2$)   
To calculate summary of all the elements in vector, we are going to be using [np.sum()](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.sum.html) 

In [23]:
J=np.sum(p_power2)
print(J)

400.0


#### Absolute value
To calculate $|M|$  -  absolute value of M - we are going to use [np.absolute()](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.absolute.html)

In [24]:
M_abs=np.absolute(M)
print(M_abs)

4


#### Square root
(Calculating $\sqrt{\frac{1}{|M|}\sum_{m=1}^{M}P_{m}^2 }$)  
[np.sqrt()](https://docs.scipy.org/doc/numpy-1.9.2/reference/generated/numpy.sqrt.html) is used to calculate square root.

In [25]:
J = J * (1 / M_abs)
J = np.sqrt(J)
print(J)

10.0


## Recap:
We have calculated Jet Lag component
$$ J  = \sqrt{\frac{1}{|M|}\sum_{m=1}^{M}P_{m}^2 }$$

$$ P_{m} = \min\left\{ 10,\;10+6cos \left( \frac{\pi\Delta J_{m}}{12}-\frac{\pi}{24}  \right) \right\} $$
using following code:

In [26]:
import numpy as np

##part1
M=4
time1 = np.array([1,2,3,4])
time2 = np.array([1,1,1,0])
delta=time1-time2
first_part=6*np.cos(np.pi*delta/12-np.pi/24)
p=np.minimum(10,10+first_part)

##part2
p_power2=np.power(p, 2)
J=np.sum(p_power2)
J=np.sqrt(J*(1/np.absolute(M)))
print(J)

10.0


## Exercise

Try calculating the second part of the metric  - distance component D
$$ D  = \frac{C_{\bigoplus}\sqrt{|M|}}{\sqrt{\sum_{l=1}^{M}d_{l}^2 }}$$

$C_{0}$ is the circumference of the Earth. We are using [scientific notation](https://chortle.ccsu.edu/java5/Notes/chap11/ch11_5.html) $40.075e3$  which means $40.075*10^3$

In [27]:
C0=40.075e3 # kilometers
print(C0)

40075.0


$d_{l}$ are the distances traveled by individual members. Initialize it randomly:

In [28]:
### your code here 

## Solution

In [17]:
d = np.array([5,6,7,8])
numerator = C0 * np.sqrt(np.absolute(M))
denominator = np.sqrt(np.sum(np.power(d, 2)))
D= numerator / denominator
print(D)

6076.155819284911


![alt text](https://github.com/callysto/callysto-sample-notebooks/blob/master/notebooks/images/Callysto_Notebook-Banners_Bottom_06.06.18.jpg?raw=true)