From the [International Math modelling challenge](https://immchallenge.org/Contests/index.html), looking at the [winning paper](https://immchallenge.org/Contests/2017/2017057.pdf) for 2017 [Jet lag problem](https://immchallenge.org/Contests/2017/Problem.html), this is productivity metric that was used:


![](images/question.png)

As part of this notebook we will demonstrate some basic  math calculations in Python, calculating the  first part of this metric :

$$ J  = \sqrt{\frac{1}{|M|}\sum_{m=1}^{M}P_{m}^2 }$$

$$ P_{m} = min\big\{ 10,10+6cos \big( \frac{\pi\Delta J_{m}}{12}-\frac{\pi}{24}  \big) \big\} $$
We will  use random input data just for demonstration purposes.  

We will write formulas in Jupyter notebook markdown cells using LateX   
(Basic LateX tutorial is located  at **getting-started/tutorials/JupyterTestdrive-LateX.ipynb**,
 Latex cheat sheet is [here](http://tug.ctan.org/info/symbols/comprehensive/symbols-a4.pdf))

### Import the numpy library
[NumPy](http://www.numpy.org) is the fundamental package for scientific computing with Python.  
[quick-start tutorial](https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html)

In [86]:
import numpy as np

First we calculate $P_{m}$ from this formula:
$$ P_{m} = min\big\{ 10,10+6cos \big( \frac{\pi\Delta J_{m}}{12}-\frac{\pi}{24}  \big) \big\} $$

We need to define number of members M. Lets set it to 4.

In [64]:
M=4

Let's define  $\Delta J_{m}$   
It should be  the shift in time zones for a given memeber m.   
So for every member we will define origin time : **time1** and destination time: **time2**, subract them and calculate the delta.

### Vectors and matricies
We will use vector of size 4(number of memebers) to define times.   
To create vectors we will use [np.array()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)
It can be used to create 1-and multi-dimensional arrays.

In [69]:
#just randomly assigning times
time1 = np.array([1,2,3,4])
time2 = np.array([1,1,1,0])
print(type(time1), time1)
print(type(time2), time2)

<class 'numpy.ndarray'> [1 2 3 4]
<class 'numpy.ndarray'> [1 1 1 0]


To  subtract one vector from another we can just minus sign.  
[Other numerical operations on arrays](http://scipy-lectures.org/intro/numpy/operations.html)

In [70]:
delta=time1-time2
print(delta)

[0 1 2 4]


Working with 2 dimentions,it's handy to use [np.matrix()](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matrix.html). More examples of ndarrays and matricies [here] (https://www.python-course.eu/matrix_arithmetic.php)

### Pi and other constants
Going back to the formula: $$ P_{m} = min\big\{ 10,10+6cos \big( \frac{\pi\Delta J_{m}}{12}-\frac{\pi}{24}  \big) \big\} $$,  to calculate $P_{m}$ we need to $\pi$, cos  and min.

**$\pi$** is defined as constant **np.pi**   
[Full list of NumPy constants](https://docs.scipy.org/doc/numpy/reference/constants.html)

In [71]:
print(np.pi)

3.141592653589793


### Math functions
[Full list of math functions](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html)
#### Cosine

To calculate cosine we will use [**np.cos()**](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cos.html)  

#### Minimum.
We will use **[np.minimum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.minimum.html)** to calcutae minimum.

Going back to the formula: $$ P_{m} = min\big\{ 10,10+6cos \big( \frac{\pi\Delta J_{m}}{12}-\frac{\pi}{24}  \big) \big\} $$, we will calculate $$ fisrt= 6cos \big( \frac{\pi\Delta J_{m}}{12}-\frac{\pi}{24}  \big) \big\} $$ first
and then: $$ P_{m} = min\big\{ 10,10+first \big\} $$

In [72]:
first=6*np.cos(np.pi*delta/12-np.pi/24)
print(first)

[5.94866917 5.94866917 5.5432772  3.65256857]


In [73]:
p=np.minimum(10,10+first)
print(p)

[10. 10. 10. 10.]


Next we are going to calculate the second part: $$ J  = \sqrt{\frac{1}{|M|}\sum_{m=1}^{M}P_{m}^2 }$$
To do it we need to way how to calculate power, summary and square root.

#### Power
To calculate power of two for the vecrtor - we can use [np.power()](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.power.html)

In [74]:
p_power2=np.power(p, 2)
print(p_power2)

[100. 100. 100. 100.]


#### Summary
To calculate summary of all the elements in vector, we are going to be using [np.sum()](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.sum.html) 

In [75]:
J=np.sum(p_power2)
print(J)

400.0


#### Square root
[np.sqrt()](https://docs.scipy.org/doc/numpy-1.9.2/reference/generated/numpy.sqrt.html) is used to calculate square root.

In [76]:
J=J*(1/M)
J=np.sqrt(J)
print(J)

10.0

### Recap:
We calculated this metric in Python assigning random initial values:
$$ J  = \sqrt{\frac{1}{|M|}\sum_{m=1}^{M}P_{m}^2 }$$

$$ P_{m} = min\big\{ 10,10+6cos \big( \frac{\pi\Delta J_{m}}{12}-\frac{\pi}{24}  \big) \big\} $$

In [81]:
import numpy as np
M=4
time1 = np.array([1,2,3,4])
time2 = np.array([1,1,1,0])
delta=time1-time2
first=6*np.cos(np.pi*delta/12-np.pi/24)
p=np.minimum(10,10+first)
p_power2=np.power(p, 2)
J=np.sum(p_power2)
J=np.sqrt(J*(1/M))
print(J)

10.0


### Exercise

Try calculating the second part of the metric  - distance component D
$$ D  = \frac{C_{0}\sqrt{|M|}}{\sqrt{\sum_{l=1}^{M}d_{l}^2 }}$$

$C_{0}$ is the circumference of the Earth.

In [83]:
C0=40.075

$d_{l}$ are the distances traveled by individual members. Initialize it randomly:

In [ ]:
### your code here 

### Solution

In [85]:
d=np.array([5,6,7,8])
numerator=C0*np.sqrt(M)
denominator=np.sqrt(np.sum(np.power(d,2)))
D=numerator/denominator
print(D)

6.076155819284911
